FROM mysql:8.0
COPY ./sql/*.sql /docker-entrypoint-initdb.d/
RUN curl -O https://raw.githubusercontent.com/alibaba/nacos/develop/config/src/main/resources/META-INF/nacos-db.sql && \ 
  mv nacos-db.sql /docker-entrypoint-initdb.d/ && \ 
  chown -R mysql:mysql /docker-entrypoint-initdb.d/
EXPOSE 3306
CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]